apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hiring-app-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saddammohd941/hiring-app-argocd.git
    targetRevision: HEAD
    path: stage
  destination:
    server: https://kubernetes.default.svc
    namespace: hiring-app-stage
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
