apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiring-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiring-app
  template:
    metadata:
      labels:
        app: hiring-app
    spec:
      containers:
      - name: hiring-app
        image: saddammohd941/hiring-app:14
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hiring-app-service
  namespace: default
spec:
  selector:
    app: hiring-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
