apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiring-app
  namespace: hiring-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiring-app
  template:
    metadata:
      labels:
        app: hiring-app
    spec:
      containers:
      - name: hiring-app
        image: saddammohd941/hiring-app:${BUILD_NUMBER}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hiring-app-service
  namespace: hiring-app-dev
spec:
  selector:
    app: hiring-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
