apiVersion: v1
kind: Service
metadata:
  name: hiring-app-nodeport
  namespace: hiring-app-prod
spec:
  type: NodePort
  ports:
    - nodePort: 32002
      port: 9000
      targetPort: 8080
  selector:
    app: hiring-app
