apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiring-app
  namespace: hiring-app-stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hiring-app
  template:
    metadata:
      labels:
        app: hiring-app
    spec:
      containers:
      - name: hiring-app
        image: saddammohd941/hiring-app:30
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.7"
            memory: "768Mi"
          requests:
            cpu: "0.3"
            memory: "384Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hiring-app-service
  namespace: hiring-app-stage
spec:
  selector:
    app: hiring-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
